# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('linkedin', models.CharField(max_length=200, null=True)),
                ('headshot', models.CharField(max_length=200, null=True)),
                ('twitter', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=1024, null=True)),
                ('twitter', models.CharField(max_length=200, null=True)),
                ('logo', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='founder',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Startup'),
        ),
    ]
